// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PostGIS_WebAPI.REPOSITORIES.Context;

#nullable disable

namespace PostGIS_WebAPI.REPOSITORIES.Migrations
{
    [DbContext(typeof(ProjectContext))]
    partial class ProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PostGIS_WebAPI.ENTITIES.Entities.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FeatureCollectionId")
                        .HasColumnType("integer");

                    b.Property<Geometry>("Geom")
                        .HasColumnType("geometry");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FeatureCollectionId");

                    b.ToTable("Feature", "public");
                });

            modelBuilder.Entity("PostGIS_WebAPI.ENTITIES.Entities.FeatureCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("FeatureCollections", "public");
                });

            modelBuilder.Entity("PostGIS_WebAPI.ENTITIES.Entities.Feature", b =>
                {
                    b.HasOne("PostGIS_WebAPI.ENTITIES.Entities.FeatureCollection", null)
                        .WithMany("Features")
                        .HasForeignKey("FeatureCollectionId");
                });

            modelBuilder.Entity("PostGIS_WebAPI.ENTITIES.Entities.FeatureCollection", b =>
                {
                    b.Navigation("Features");
                });
#pragma warning restore 612, 618
        }
    }
}
